definitions:
  dto.AdminInfoOutput:
    properties:
      avatar:
        description: 头像
        type: string
      id:
        description: id
        type: integer
      introduction:
        description: 简介
        type: string
      login_time:
        description: 登录时间
        type: string
      roles:
        description: 角色
        items:
          type: string
        type: array
      user_name:
        description: 账户
        type: string
    type: object
  dto.AdminLoginInput:
    properties:
      password:
        example: 密码
        type: string
      username:
        example: 账户
        type: string
    required:
    - password
    - username
    type: object
  dto.AdminLoginOutput:
    properties:
      token:
        example: token
        type: string
    type: object
  dto.ChangePwdInput:
    properties:
      password:
        example: 密码
        type: string
    required:
    - password
    type: object
  dto.HostListItemOutput:
    properties:
      domain:
        description: 主机名
        type: string
      domain_desc:
        description: 主机描述
        type: string
      domain_ip:
        description: 主机ip
        type: string
      domain_os:
        description: 操作系统
        type: string
      domain_type:
        description: 主机类型:0真机,1云机,2虚拟机
        type: integer
      host_desc:
        description: 宿主机描述
        type: string
      host_ip:
        description: 宿主机ip
        type: string
      id:
        description: id
        type: integer
    type: object
  dto.HostListOutput:
    properties:
      list:
        description: 列表
        items:
          $ref: '#/definitions/dto.HostListItemOutput'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  dto.HostStatusOutput:
    properties:
      domain:
        description: 域
        type: string
      errmsg:
        description: 错误信息
        type: string
      host_ip:
        description: 宿主机名
        type: string
      isRunning:
        description: 状态信息 bool
        type: boolean
      status:
        description: 状态信息 bool
        type: boolean
    type: object
  dto.ServiceAddHTTPInput:
    properties:
      black_list:
        description: 黑名单ip
        type: string
      clientip_flow_limit:
        description: 客户端ip限流
        type: integer
      header_transfor:
        description: Header头转换
        type: string
      ip_list:
        description: ip列表
        type: string
      need_https:
        description: 是否支持https
        type: integer
      need_strip_uri:
        description: 启用strip_uri
        type: integer
      need_websocket:
        description: 是否支持websocket
        type: integer
      open_auth:
        description: 是否开启权限
        type: integer
      round_type:
        description: 轮询方式
        type: integer
      rule:
        description: 接入路径
        type: string
      rule_type:
        description: 接入类型
        type: integer
      service_desc:
        description: 服务描述
        type: string
      service_flow_limit:
        description: 服务端ip限流
        type: integer
      service_name:
        description: 服务名
        type: string
      upstream_connect_timeout:
        description: 建立连接超时(秒)
        type: integer
      upstream_header_timeout:
        description: 获取header超时(秒)
        type: integer
      upstream_idle_timeout:
        description: 连接最大空闲时间(秒)
        type: integer
      upstream_max_idle:
        description: 最大空闲连接数
        type: integer
      url_rewrite:
        description: URL重写
        type: string
      weight_list:
        description: 权重列表
        type: string
      white_list:
        description: 白名单ip
        type: string
    required:
    - ip_list
    - rule
    - service_desc
    - service_name
    - weight_list
    type: object
  dto.ServiceListItemOutput:
    properties:
      id:
        description: id
        type: integer
      load_type:
        description: 类型
        type: integer
      qpd:
        description: qpd
        type: integer
      qps:
        description: qps
        type: integer
      service_addr:
        description: 服务地址
        type: string
      service_desc:
        description: 服务描述
        type: string
      service_name:
        description: 服务名称
        type: string
      total_node:
        description: 节点数
        type: integer
    type: object
  dto.ServiceListOutput:
    properties:
      list:
        description: 列表
        items:
          $ref: '#/definitions/dto.ServiceListItemOutput'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  middleware.Response:
    properties:
      data:
        type: object
      errmsg:
        type: string
      errno:
        type: integer
      stack:
        type: object
      trace_id:
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /admin/admin_info:
    get:
      consumes:
      - application/json
      description: 管理员信息
      operationId: /admin/admin_info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      summary: 管理员信息
      tags:
      - 管理员接口
  /admin/change_pwd:
    post:
      consumes:
      - application/json
      description: 修改密码
      operationId: /admin/change_pwd
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePwdInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 修改密码
      tags:
      - 管理员接口
  /admin_login/login:
    post:
      consumes:
      - application/json
      description: 管理员登录
      operationId: /admin_login/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: 管理员登录
      tags:
      - 管理员接口
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: 管理员退出
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 管理员退出
      tags:
      - 管理员接口
  /host/control/recover:
    put:
      consumes:
      - application/json
      description: 还原域
      operationId: /host/control/recovery
      parameters:
      - description: 域名
        in: query
        name: domain
        required: true
        type: string
      - description: 宿主机ip
        in: query
        name: host_ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HostStatusOutput'
              type: object
      summary: 还原域
      tags:
      - 主机管理
  /host/control/shutdown:
    put:
      consumes:
      - application/json
      description: 关闭域
      operationId: /host/control/shutdown
      parameters:
      - description: 域名
        in: query
        name: domain
        required: true
        type: string
      - description: 宿主机ip
        in: query
        name: host_ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HostStatusOutput'
              type: object
      summary: 关闭域
      tags:
      - 主机管理
  /host/control/start:
    put:
      consumes:
      - application/json
      description: 启动域
      operationId: /host/control/start
      parameters:
      - description: 域名
        in: query
        name: domain
        required: true
        type: string
      - description: 宿主机ip
        in: query
        name: host_ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HostStatusOutput'
              type: object
      summary: 启动域
      tags:
      - 主机管理
  /host/control/status:
    get:
      consumes:
      - application/json
      description: 域状态
      operationId: /host/control/status
      parameters:
      - description: 域名
        in: query
        name: domain
        required: true
        type: string
      - description: 宿主机ip
        in: query
        name: host_ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HostStatusOutput'
              type: object
      summary: 域状态
      tags:
      - 主机管理
  /host/host_list:
    get:
      consumes:
      - application/json
      description: 主机列表
      operationId: /host/host_list
      parameters:
      - description: 关键词
        in: query
        name: info
        type: string
      - description: 每页个数
        in: query
        name: page_size
        required: true
        type: integer
      - description: 当前页数
        in: query
        name: page_no
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.HostListOutput'
              type: object
      summary: 主机列表
      tags:
      - 主机管理
  /service/service:
    delete:
      consumes:
      - application/json
      description: 服务删除
      operationId: /service/service
      parameters:
      - description: 服务ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 服务删除
      tags:
      - 服务管理
  /service/service/http:
    post:
      consumes:
      - application/json
      description: 添加HTTP服务
      operationId: /service/service/http/post
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ServiceAddHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 添加HTTP服务
      tags:
      - 服务管理
    put:
      consumes:
      - application/json
      description: 修改HTTP服务
      operationId: /service/service/http/put
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ServiceAddHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 修改HTTP服务
      tags:
      - 服务管理
  /service/service_list:
    get:
      consumes:
      - application/json
      description: 服务列表
      operationId: /service/service_list
      parameters:
      - description: 关键词
        in: query
        name: info
        type: string
      - description: 每页个数
        in: query
        name: page_size
        required: true
        type: integer
      - description: 当前页数
        in: query
        name: page_no
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ServiceListOutput'
              type: object
      summary: 服务列表
      tags:
      - 服务管理
swagger: "2.0"
